name: Build and test

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install system dependencies
      run: sudo apt-get install -y git cmake make gcc g++ libssl-dev
    - name: Install mgclient
      uses: actions/checkout@master
      with:
          repository: memgraph/mgclient
      run: |
        ls
        cd mgclient
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
    - name: Install and build addon
      working-directory: ./
      run: |
        npm install
