name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install system dependencies
      run: sudo apt-get install -y git cmake make gcc g++ libssl-dev
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and build addon
      run: |
        npm install
        npm run build:release
    - name: Lint JS code
      run: |
        npm run lint
        npm run test
