name: CI

on: [push]

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Install system dependencies
      run: sudo apt-get install -y git cmake make gcc g++ libssl-dev
    - name: Download mgclient
      uses: actions/checkout@master
      with:
        repository: memgraph/mgclient
    - name: Install mgclient
      run: |
        mkdir build
        cd build
        cmake ..
        make
        sudo make install
    - uses: actions/checkout@v1
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install and build addon
      run: |
        npm install
        npm run build:release
    - name: Lint JS code
      run: |
        npm run lint
    - name: Cache Memgraph Docker image
      id: cache-memgraph-docker
      uses: actions/cache@v1
      with:
        path: ~/memgraph
        key: cache-memgraph-v1.0.0-docker-image
    - name: Download Memgraph Docker image
      if: steps.cache-memgraph-docker.outputs.cache-hit != 'true'
      run: |
        mkdir ~/memgraph
        curl -L https://memgraph.com/download/memgraph/v1.0.0/memgraph-1.0.0-community-docker.tar.gz > ~/memgraph/memgraph-docker.tar.gz
    - name: Load Memgraph Docker image
      run: |
        docker load -i ~/memgraph/memgraph-docker.tar.gz
    - name: Run JS tests
      run: |
        npm run test
